In [1]:
from PartSegCore_compiled_backend.fast_unique import label_unique
import numpy as np

In [2]:
data = np.random.randint(0, 100, (1000, 1000), dtype=np.uint8)
data1 = np.random.randint(0, 100, (1000, 1000), dtype=np.uint16)
data2 = np.random.randint(0, 5, (1000, 1000), dtype=np.uint8)
data3 = np.random.randint(0, 100, (10, 1000, 1000), dtype=np.uint8)
data4 = np.random.randint(0, 5, (10, 1000, 1000), dtype=np.uint8)
data5 = np.zeros((1000, 1000), dtype=np.uint8)
data5[20:200, 30:100] = 1
data5[320:500, 30:100] = 2
data5[20:200, 230:4100] = 180
data6 = np.zeros((30, 1000, 1000), dtype=np.uint8)
data6[:, 20:200, 30:100] = 1
data6[:, 320:500, 30:100] = 2
data6[:, 20:200, 230:4100] = 200

In [3]:
%timeit np.unique(data)
%timeit label_unique(data, numpy_fallback=False)

26.8 ms ± 316 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
3.33 ms ± 1.92 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
%timeit np.unique(data1)
%timeit label_unique(data1, numpy_fallback=False)

33.1 ms ± 1.28 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
49 ms ± 3.21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
%timeit np.unique(data2)
%timeit label_unique(data2, numpy_fallback=False)

14.9 ms ± 252 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
2.08 ms ± 149 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [6]:
%timeit np.unique(data3)
%timeit label_unique(data3, numpy_fallback=False)

262 ms ± 919 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
22.6 ms ± 1.67 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
%timeit np.unique(data4)
%timeit label_unique(data4, numpy_fallback=False)

162 ms ± 1.77 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
20.6 ms ± 1.69 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
%timeit np.unique(data5)
%timeit label_unique(data5, numpy_fallback=False)

7.16 ms ± 30.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
The slowest run took 7.90 times longer than the fastest. This could mean that an intermediate result is being cached.
876 µs ± 925 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [9]:
print(label_unique(data5, numpy_fallback=False))
print(np.unique(data5))

[  0   1   2 180]
[  0   1   2 180]


In [10]:
%timeit label_unique(data6, numpy_fallback=False)
%timeit np.unique(data6)

10.5 ms ± 714 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
278 ms ± 1.08 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
print(label_unique(data6, numpy_fallback=False))
print(np.unique(data6))

[  0   1   2 200]
[  0   1   2 200]
