In [1]:
from PartSegCore_compiled_backend.fast_unique import label_unique
import numpy as np
import pandas as pd

In [2]:
data = np.random.randint(0, 100, (1000, 1000), dtype=np.uint8)
data1 = np.random.randint(0, 100, (1000, 1000), dtype=np.uint16)
data2 = np.random.randint(0, 5, (1000, 1000), dtype=np.uint8)
data3 = np.random.randint(0, 100, (10, 1000, 1000), dtype=np.uint8)
data4 = np.random.randint(0, 5, (10, 1000, 1000), dtype=np.uint8)
data5 = np.zeros((1000, 1000), dtype=np.uint8)
data5[20:200, 30:100] = 1
data5[320:500, 30:100] = 2
data5[20:200, 230:4100] = 180
data6 = np.zeros((30, 1000, 1000), dtype=np.uint8)
data6[:, 20:200, 30:100] = 1
data6[:, 320:500, 30:100] = 2
data6[:, 20:200, 230:4100] = 200

In [3]:
%timeit np.unique(data)
%timeit label_unique(data, numpy_fallback=False)
%timeit pd.unique(data.ravel())

26.9 ms ± 407 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
4.81 ms ± 2.3 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
3.14 ms ± 67.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
%timeit np.unique(data1)
%timeit label_unique(data1, numpy_fallback=False)
%timeit pd.unique(data1.ravel())

30.5 ms ± 343 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
5.77 ms ± 3.19 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
3.3 ms ± 103 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
%timeit np.unique(data2)
%timeit label_unique(data2, numpy_fallback=False)
%timeit pd.unique(data2.ravel())

15 ms ± 159 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
6.33 ms ± 2.25 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
3.42 ms ± 242 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
%timeit np.unique(data3)
%timeit label_unique(data3, numpy_fallback=False)
%timeit pd.unique(data3.ravel())

279 ms ± 5.74 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
30.1 ms ± 4.64 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
32.6 ms ± 1.77 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
%timeit np.unique(data4)
%timeit label_unique(data4, numpy_fallback=False)
%timeit pd.unique(data4.ravel())

163 ms ± 1.13 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
27.6 ms ± 6.19 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
30.5 ms ± 447 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
%timeit np.unique(data5)
%timeit label_unique(data5, numpy_fallback=False)
%timeit pd.unique(data5.ravel())

7.4 ms ± 113 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
The slowest run took 4.54 times longer than the fastest. This could mean that an intermediate result is being cached.
1.59 ms ± 863 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
3.15 ms ± 97.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
print(label_unique(data5, numpy_fallback=False))
print(np.unique(data5))
print(pd.unique(data5.ravel()))

[  0   1   2 180]
[  0   1   2 180]
[  0   1 180   2]


In [10]:
%timeit label_unique(data6, numpy_fallback=False)
%timeit np.unique(data6)
%timeit pd.unique(data6.ravel())

21.7 ms ± 6.34 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
307 ms ± 33.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
92.3 ms ± 1.14 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
print(label_unique(data6, numpy_fallback=False))
print(np.unique(data6))
print(pd.unique(data6.ravel()))

[  0   1   2 200]
[  0   1   2 200]
[  0   1 200   2]
